### ISSUE TITLE
Trouble running it

### ISSUE THREAD

**Issue by sidrafarooq** [chenzhifei731/Pysmell#1]
Hi,

As stated by you that we need to specify directory in parameter.py i did that but the subjects folder is empty as well do we need to add required project version copies in subject folder as well?

Thank you

**Comment by correiajoao** [comment]
Hi, @sidrafarooq

Can you provide any additional comments on how to run the tool? I have tried it, but I am not successful.

Thanks in advance.

**Comment by sidrafarooq** [comment]
@correiajoao 

You have to set parameter.py
Add proper path for subject_dir and this directory must contains all the projects you want to run pysmell for.
With in directory: add project name with their versions.

and now you can run the project, all the files having 
`from parameter import subject_dir`
can be run by using python and that file name

by running project_info.py you will get each projects files information
by running metrics_explore.py metrics folder will be populated for each code smell in their own csv files.

**Comment by sidrafarooq** [comment]
@correiajoao you have to use python 2.7 for this project to work.

**Comment by correiajoao** [comment]
@sidrafarooq thank you very much!!

I followed your tips and got it running. 

In addition to what you said,  for non-windows users to check the file paths, the code uses the pattern with "\".

**Comment by sidrafarooq** [comment]
> @sidrafarooq thank you very much!!
> 
> I followed your tips and got it running.
> 
> In addition to what you said, for non-windows users to check the file paths, the code uses the pattern with "".

I use windows for running the project and yes for linux you have to make path in a different way.
and you welcome.

**Comment by ykazemi** [comment]
@sidrafarooq Hi, I followed your instruction however, when I want to run metric_explore I get this error:

 File "/Pysmell-master/pysmell/detection/metric_explore.py", line 128, in <module>
    outliers = pyplot.boxplot(metricdata)['fliers'][0].get_data()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 2574, in boxplot
    usermedians=usermedians, conf_intervals=conf_intervals)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 5967, in boxplot
    if not hasattr(x[0], '__len__'):
IndexError: list index out of range

**Comment by ShrishtiKarkera** [comment]
Is there a revised version in python 3 and later?
